### VERSIONS ###
[versions]
microprofile = "7.1"
jackson = "2.19.2"
webjars-jquery = "3.7.1"
webjars-bootstrap = "5.3.7"
webjars-popper = "2.11.7"
webjars-locator = "0.52"
webjars-fontawesome = "7.0.0"
junit = "5.13.4"
kotest = "6.0.0"
mockk = "1.14.5"
liberty = "3.9.4"

### LIBRARIES ###
[libraries]
# Kotlin
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
# Microprofile
microprofile = { module = "org.eclipse.microprofile:microprofile", version.ref = "microprofile" }
# Liberty
liberty-gradle-plugin = { module = "io.openliberty.tools:liberty-gradle-plugin", version.ref = "liberty" }
# Spring Boot
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
# Spring Security
spring-security-oauth2-authorization-server = { module = "org.springframework.security:spring-security-oauth2-authorization-server" }
# Jackson
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-dataformat-csv = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv", version.ref = "jackson" }
# Webjars
webjars-jquery = { module = "org.webjars:jquery", version.ref = "webjars-jquery" }
webjars-bootstrap = { module = "org.webjars:bootstrap", version.ref = "webjars-bootstrap" }
webjars-popper = { module = "org.webjars:popper.js", version.ref = "webjars-popper" }
webjars-locator = { module = "org.webjars:webjars-locator", version.ref = "webjars-locator" }
webjars-fontawesome = { module = "org.webjars:font-awesome", version.ref = "webjars-fontawesome" }
# JUnit
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
# Kotest
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
# Mockk
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

### BUNDLES ###
[bundles]
jackson = [
    "jackson-module-kotlin",
    "jackson-datatype-jsr310"
]
webjars = [
    "webjars-jquery",
    "webjars-bootstrap",
    "webjars-popper",
    "webjars-locator",
    "webjars-fontawesome"
]
junit = [
    "kotlin-test-junit",
    "junit-jupiter",
    "junit-platform-launcher"
]
kotest = [
    "kotest-runner-junit5",
    "kotest-assertions-core",
    "kotest-property"
]